# Generated by Django 5.1.6 on 2025-04-21 16:34

import django.db.models.deletion
import firstapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='major_required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='university',
            field=models.ForeignKey(default=firstapp.models.get_default_university, on_delete=django.db.models.deletion.CASCADE, to='firstapp.university'),
        ),
    ]
