# Generated by Django 5.1.6 on 2025-04-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_alter_reply_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_student',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
