# Generated by Django 5.1.6 on 2025-03-28 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_customuser_alter_admin_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
