# Generated by Django 5.1.5 on 2025-04-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_remove_customuser_username_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='gender',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
