# Generated by Django 5.1.5 on 2025-04-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_studentprofile_date_of_birth_studentprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='gender',
        ),
    ]
