# Generated by Django 5.1.5 on 2025-04-02 11:54

import firstapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_remove_studentprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(default=firstapp.models.generate_student_id, max_length=20, unique=True),
        ),
    ]
